Status banner
brown-ccv/ccv-website pull request #27
Opened 2024-12-05 22:20 UTC by hetd54

<img width="1518" alt="Screenshot 2024-12-05 at 5 12 32 PM" src="https://github.com/user-attachments/assets/92f9bf20-f3ce-44a0-a2eb-f942569e0572">

<img width="1522" alt="Screenshot 2024-12-05 at 5 20 10 PM" src="https://github.com/user-attachments/assets/16dfa32b-34b8-4679-89b0-00521348b01f">

2024-12-05 22:32 UTC, s-bessey requested changes
A couple of nitpicks!

2024-12-05 22:32 UTC, s-bessey commented on components/header/utils.ts
> +      const comments = await octokit.request(
No need to get the issue comments here!

2024-12-05 22:32 UTC, s-bessey commented on components/header/Header.tsx
> +  // uncomment to test banner with no open issues
I'm a little confused about the comment vs uncomment for testing here? Might be good to make that a little clearer

2024-12-05 23:13 UTC, hetd54 commented
Gradient with green and blue colors
<img width="1651" alt="Screenshot 2024-12-05 at 6 12 22 PM" src="https://github.com/user-attachments/assets/5a04b3dc-daeb-4909-a90f-fac550e8e185">

2024-12-06 20:49 UTC, eldu commented
@hetd54 @s-bessey 
I think we'll want to streamline the language we're using. It seems like we're using issues/incidents interchangeably. Let's keep it consistent with the status page and the website?

Also,
When all services are operational "View Issues" doesn't seem to make sense since issues could imply something is wrong.
Maybe instead of "View Issues", "View Status"?

2024-12-10 16:53 UTC, s-bessey commented
I think the current color blends a bit too much with the rest of the page -- I'd say something a bit darker and without _too_ much contrast between the "top" and "bottom" of the gradient

2024-12-13 17:02 UTC, s-bessey approved these changes
Looking good!

2024-12-13 17:02 UTC, s-bessey commented on components/header/Banner.tsx
> +// Try red/orange for the error gradient
remove comment?

2024-12-13 17:02 UTC, s-bessey commented on components/header/Header.tsx
> +// Green/orange dot?? See if that feels like recording
Still some notes to self?

2024-12-13 21:14 UTC, merged